[theme]
primaryColor="#6C63FF"            # accent purple/blue for buttons, sliders
backgroundColor="#001D7E"         # deep navy blue (matches your slide)
secondaryBackgroundColor="#0A2BA0" # slightly lighter blue for panels/sidebar
textColor="#FFFFFF"               # white text
font="sans serif"
